import("functions.rb")

desc "Build"
lane :build do
  gradle(task: "assembleDebug")
end

desc "Create new tag"
lane :tag do |options|

    # Create a new tag
    add_git_tag(tag: options[:version])

    # Push tag to remote
    push_git_tags(tag: options[:version])
end
