on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  ##########################################################
  # Lint Job:
  # Install dependencies and execute lint debug
  ##########################################################
  build-debug:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: F`astlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.0'

      - name: Assemble Debug
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'build'

  linters:
    needs: build-debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Productlist Unit Tests
        run: ./gradlew lint detekt

  unit-tests:
    needs: build-debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Productlist Unit Tests
        run: ./gradlew :productlist:testDebugUnitTest

  tag:
    name: Tag
    needs: [linters, unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v0.0.2",
              sha: context.sha
            })