on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: F`astlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.0'

      - name: Assemble Debug
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'build'

  apk:
    name: Generate APK
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.0'

      - name: Assemble Debug
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'build'

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk